const K='kl3',M=6e4,$=s=>document.querySelector(s);
const esc=s=>String(s==null?'':s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const T=t=>new Date(t).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});
let S,tab='home',sub='',ui={f:{},cat:'General',q:'',msg:'',cn:'',ok:0,hz:'',so:'near',br:'Malanday',cb:'Malanday',sel:'',dis:0};
const IC=p=>`<svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${p}</svg>`;
const HI=['<path d="M12 3L2 20h20z"/><path d="M12 9v5M12 17h.01"/>','<path d="M3 21h18M5 21V9l7-5 7 5v12"/><path d="M10 21v-6h4v6"/>','<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="3.5"/><path d="M5.6 5.6l3.9 3.9M14.5 14.5l3.9 3.9M18.4 5.6l-3.9 3.9M9.5 14.5l-3.9 3.9"/>','<rect x="3" y="3" width="18" height="18" rx="4"/><path d="M12 8v8M8 12h8"/>','<path d="M3 8l9-5 9 5v8l-9 5-9-5z"/><path d="M3 8l9 5 9-5M12 13v8"/>','<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7.5h.01"/>'];
const NV=[['home','Shelters','<path d="M9 6h12M9 12h12M9 18h12M4 6h.01M4 12h.01M4 18h.01"/>'],['map','Map View','<path d="M9 4L3 6v14l6-2 6 2 6-2V4l-6 2z"/><path d="M9 4v14M15 6v14"/>'],['assist','Help',HI[2]],['relief','Relief',HI[4]],['more','Settings','<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M19.1 4.9L17 7M7 17l-2.1 2.1"/>']];
const HZ=[['flood'],['flood'],['flood','fire'],['quake','fire'],['flood'],['fire','quake']];
const TT={home:'Kanlungan',map:'Map View',assist:'Request help',relief:'Relief',more:'Settings'},ST={danger:'Immediate danger',info:'Emergency info',al:'Alerts',q:'Pending actions',about:'About',coord:'Coordinator',ctr:'Center details'};
const FL=[['ramp','Ramp access'],['gn','Gender-neutral facilities'],['med','Medical support'],['wat','Water'],['chg','Charging'],['kid','Child-safe area'],['slp','Sleeping area']];
const CATS=['General','Medical','Accessibility','Child','Water/Sanitation','Relief','Other'];
const BR=[
['Barangka',1,['Barangka Elementary School','Barangka Covered Court / Basketball Field'],['Kalumpang Elementary School','Jesus dela Peña Elementary School']],
['Calumpang',1,['Kalumpang Elementary School','Kalumpang National High School'],['San Roque National High School','Barangka Elementary School']],
['Industrial Valley Complex (IVC)',1,['IVC Covered Court','IVC Safety Center (Major Dizon Road)'],['Barangka Elementary School','Marikina Elementary School']],
['Jesus dela Peña',1,['Jesus dela Peña Elementary School','Leodegario Victorino Elementary School'],['Tañong Elementary School','Barangka Elementary School']],
['Malanday',1,['Malanday Elementary School','Bulelak Gym / Covered Court','Sampaguita Gym / Covered Court'],['Parang Elementary School Open Grounds','Parang Gym','Concepcion Elementary School']],
['San Roque',1,['San Roque Elementary School','San Roque National High School'],['Sta. Elena High School','Kalumpang National High School']],
['Sta. Elena',1,['Sta. Elena High School','Marikina Elementary School'],['Sto. Niño Elementary School','San Roque Elementary School']],
['Sto. Niño',1,['Sto. Niño Elementary School','Sto. Niño National High School'],['H. Bautista Elementary School','Manotoc Gym']],
['Tañong',1,['Tañong High School','Tañong Elementary School','Tañong Gym'],['Jesus dela Peña Elementary School']],
['Concepcion Uno',2,['H. Bautista Elementary School','Concepcion Elementary School','Concepcion Integrated School (CIS) Main & San Lorenzo Campus'],['Parang Elementary School Open Grounds','Marikina Sports Center']],
['Concepcion Dos',2,['SSS Village Elementary School (SSSVES)','Marikina Sports Center'],['Marikina Heights Barangay Gym','H. Bautista Elementary School']],
['Fortune',2,['Fortune High School','Fortune Elementary School'],['Parang Elementary School Open Grounds','Marikina Heights Barangay Gym']],
['Marikina Heights',2,['Fairlane Multi-Purpose Hall / Covered Court','Marikina Heights Barangay Gym'],['SSS Village Elementary School (SSSVES)','Parang Gym']],
['Nangka',2,['Nangka Elementary School','Nangka Barangay Gym','Filipinas Gym'],['Parang Elementary School Open Grounds','H. Bautista Elementary School']],
['Parang',2,['Parang Gym','Parang Elementary School Open Grounds'],['Fortune Elementary School','H. Bautista Elementary School']],
['Tumana',2,['Woodrich Village Open Space','Farmers I & Iwahig Safe Zones'],['Concepcion Integrated School (CIS) Main & San Lorenzo Campus','Malanday Elementary School']]];
/* every shelter once, with the barangay it is located in */
const SH=[['Barangka Elementary School','Barangka'],['Barangka Covered Court / Basketball Field','Barangka'],['Kalumpang Elementary School','Calumpang'],['Kalumpang National High School','Calumpang'],['IVC Covered Court','Industrial Valley Complex (IVC)'],['IVC Safety Center (Major Dizon Road)','Industrial Valley Complex (IVC)'],['Jesus dela Peña Elementary School','Jesus dela Peña'],['Leodegario Victorino Elementary School','Jesus dela Peña'],['Malanday Elementary School','Malanday'],['Bulelak Gym / Covered Court','Malanday'],['Sampaguita Gym / Covered Court','Malanday'],['San Roque Elementary School','San Roque'],['San Roque National High School','San Roque'],['Sta. Elena High School','Sta. Elena'],['Marikina Elementary School','Sta. Elena'],['Sto. Niño Elementary School','Sto. Niño'],['Sto. Niño National High School','Sto. Niño'],['Tañong High School','Tañong'],['Tañong Elementary School','Tañong'],['Tañong Gym','Tañong'],['H. Bautista Elementary School','Concepcion Uno'],['Concepcion Elementary School','Concepcion Uno'],['Concepcion Integrated School (CIS) Main & San Lorenzo Campus','Concepcion Uno'],['SSS Village Elementary School (SSSVES)','Concepcion Dos'],['Marikina Sports Center','Concepcion Dos'],['Fortune High School','Fortune'],['Fortune Elementary School','Fortune'],['Fairlane Multi-Purpose Hall / Covered Court','Marikina Heights'],['Marikina Heights Barangay Gym','Marikina Heights'],['Manotoc Gym','Marikina Heights'],['Nangka Elementary School','Nangka'],['Nangka Barangay Gym','Nangka'],['Filipinas Gym','Nangka'],['Parang Gym','Parang'],['Parang Elementary School Open Grounds','Parang'],['Woodrich Village Open Space','Tumana'],['Farmers I & Iwahig Safe Zones','Tumana']];
const ID={};SH.forEach(([n],i)=>ID[n]='c'+(i+1));
const GEO={'Barangka':[14.6327,121.0821],'Calumpang':[14.6249,121.0865],'Industrial Valley Complex (IVC)':[14.6271,121.0800],'Jesus dela Peña':[14.6367,121.0910],'Malanday':[14.6500,121.0941],'San Roque':[14.6281,121.0984],'Sta. Elena':[14.6328,121.0977],'Sto. Niño':[14.6367,121.0973],'Tañong':[14.6344,121.0867],'Concepcion Uno':[14.6497,121.1020],'Concepcion Dos':[14.6386,121.1117],'Fortune':[14.6632,121.1274],'Marikina Heights':[14.6501,121.1170],'Nangka':[14.6726,121.1092],'Parang':[14.6590,121.1123],'Tumana':[14.6562,121.0973]};
const BI={},BP={};BR.forEach(([n,d,P,N],i)=>{BI[n]={p:P.map(x=>ID[x]),n:N.map(x=>ID[x])};BP[n]=GEO[n]});
const brOpts=(sel,pre='')=>[1,2].map(d=>`<optgroup label="District ${d}">${BR.filter(b=>b[1]===d).map(b=>`<option value="${esc(b[0])}"${b[0]===sel?' selected':''}>${pre}${esc(b[0])}</option>`).join('')}</optgroup>`).join('');
const hs=s=>{let x=2166136261;for(const ch of s)x=Math.imul(x^ch.charCodeAt(0),16777619);return x>>>0};
const HZS=[['flood'],['flood','fire'],['quake','fire'],['fire','quake'],['flood','quake'],['flood']];
const NOTE={s:'School building. Classrooms serve as sleeping areas. Capacity, headcount and facilities are simulated.',o:'Open-air site with tents. Capacity, headcount and facilities are simulated.',h:'Covered court or hall with open floor space for sleeping bays. Capacity, headcount and facilities are simulated.'};
const CS=t=>{const cnt={},idx={};SH.forEach(([n,a])=>cnt[a]=(cnt[a]||0)+1);
return SH.map(([n,a],i)=>{const h=hs(n),ty=/Open|Safe|Grounds/.test(n)?'o':/School/.test(n)?'s':'h',k=idx[a]=(idx[a]||0)+1,m=cnt[a],ang=(k-1)*2*Math.PI/m-Math.PI/2,r=m>1?150:0,
cap=Math.round((ty==='s'?300+h%300:ty==='o'?100+h%200:150+h%300)/10)*10,occ=Math.round(cap*(.12+((h>>>8)%86)/100)),b=j=>(h>>>(12+j))&1;
return{id:'c'+(i+1),n,a,cap,occ,u:t-(5+(h>>>4)%55)*M,ramp:b(0),gn:b(1)&b(2),med:b(3)&b(4),wat:b(5)|b(6),chg:b(7),kid:b(8)&b(9),slp:1,off:0,note:NOTE[ty],lat:+(BP[a][0]+r*Math.sin(ang)/111320).toFixed(5),lng:+(BP[a][1]+r*Math.cos(ang)/(111320*Math.cos(BP[a][0]*Math.PI/180))).toFixed(5),hz:HZS[h%6]}})};
const seed=()=>{const t=Date.now(),C=(id,n,a,cap,occ,m,f,note,x,y)=>({id,n,a,cap,occ,u:t-m*M,ramp:f[0],gn:f[1],med:f[2],wat:f[3],chg:f[4],kid:f[5],slp:f[6],off:0,note,x,y});
return{sim:0,coord:0,last:t,fam:[],req:[],act:[],q:[],pref:{Service:1,Information:1},
c:CS(t),
inv:[{id:'i1',n:'Rice (packs)',q:120,lo:40,cr:15,u:t-30*M},{id:'i2',n:'Bottled water (liters)',q:300,lo:100,cr:30,u:t-30*M},{id:'i3',n:'Hygiene kits',q:40,lo:20,cr:8,u:t-30*M},{id:'i4',n:'Blankets',q:18,lo:20,cr:8,u:t-30*M},{id:'i5',n:'Canned goods',q:60,lo:30,cr:10,u:t-30*M},{id:'i6',n:'First-aid kits',q:3,lo:10,cr:4,u:t-30*M}],
al:[{id:1,cat:'Emergency',t:'DEMO ALERT: sample evacuation announcement',b:'Simulated for the prototype. This is not a real alert.',at:t-45*M},{id:2,cat:'Service',t:'Demo alert: assistance desk hours',b:'Simulated service notice. Not real.',at:t-30*M},{id:3,cat:'Information',t:'Demo alert: relief schedule',b:'Simulated announcement. Not real.',at:t-20*M}]}};
try{S=JSON.parse(localStorage.getItem(K))}catch(e){}
if(!S||!S.c||!S.c[0].hz||!S.c[0].lat)S=seed();
const on=()=>navigator.onLine&&!S.sim;
const save=()=>{try{localStorage.setItem(K,JSON.stringify(S))}catch(e){}};
const cs=c=>{const p=c.occ/c.cap;return c.off?'TEMPORARILY UNAVAILABLE':p>=.98?'FULL':p>=.7?'NEARLY FULL':'AVAILABLE'};
const is=i=>i.q<=0?'OUT OF STOCK':i.q<=i.cr?'CRITICAL':i.q<=i.lo?'LOW STOCK':'IN STOCK';
const BD={'AVAILABLE':['ok','✓'],'NEARLY FULL':['wn','!'],'FULL':['bd','✕'],'TEMPORARILY UNAVAILABLE':['mu','–'],'IN STOCK':['ok','✓'],'LOW STOCK':['wn','!'],'CRITICAL':['bd','✕'],'OUT OF STOCK':['bd','✕'],'PENDING':['wn','…'],'ASSIGNED':['mu','→'],'IN PROGRESS':['wn','…'],'RESOLVED':['ok','✓'],'PENDING SYNC':['wn','…'],'SYNCING':['wn','↻'],'SYNCHRONIZED':['ok','✓'],'SYNC FAILED':['bd','✕']};
const bg=s=>`<span class="badge ${BD[s][0]}">${BD[s][1]} ${s}</span>`;
const fr=t=>`<p class="mu s">${on()?'Last updated':'Last known'}: ${T(t)}${!on()||Date.now()-t>30*M?' <b class="wn">· May be outdated</b>':''}</p>`;
const log=x=>{S.act.unshift({t:Date.now(),x});S.act.length=Math.min(S.act.length,30);if(on()){S.last=Date.now();return 0}const id='Q'+Date.now()+Math.random().toString(36).slice(2,5);S.q.push({id,x,s:'PENDING SYNC',t:Date.now()});return id};
const qs=q=>{const i=q&&S.q.find(x=>x.id===q);return i?bg(i.s):''};
const msg=m=>{ui.msg=m};
const co=sel=>{const b=BI[ui.br],ids=[...b.p,...b.n],o=c=>`<option value="${c.id}"${c.id===sel?' selected':''}>${esc(c.n)}</option>`;return`<optgroup label="Brgy. ${esc(ui.br)}: primary and nearby">${grp(ids).map(o).join('')}</optgroup><optgroup label="Other centers">${S.c.filter(c=>!ids.includes(c.id)).map(o).join('')}</optgroup>`};
const qr=id=>{try{const q=qrcode(0,'M');q.addData(id);q.make();return`<div class="qr" role="img" aria-label="QR code for ${id}">${q.createSvgTag({scalable:true})}</div>`}catch(e){return`<p class="s">QR image could not load. Show this ID instead: <b>${id}</b></p>`}};
function go(t,s){tab=t;sub=s||'';ui.msg='';ui.ok=0;R();scrollTo(0,0)}
function sync(){if(!on())return;const p=S.q.filter(x=>x.s==='PENDING SYNC'||x.s==='SYNC FAILED');if(!p.length){S.last=Date.now();R();return}
p.forEach(x=>x.s='SYNCING');R();setTimeout(()=>{S.q.forEach(x=>{if(x.s==='SYNCING')x.s='SYNCHRONIZED'});const d=S.q.filter(x=>x.s==='SYNCHRONIZED');if(d.length>12)S.q=S.q.filter(x=>x.s!=='SYNCHRONIZED'||d.slice(-12).includes(x));S.last=Date.now();R()},1500)}
const dist=c=>{const h=BP[ui.br]||[14.6331,121.0993],r=Math.PI/180,a=(c.lat-h[0])*r,b=(c.lng-h[1])*r,q=Math.sin(a/2)**2+Math.cos(h[0]*r)*Math.cos(c.lat*r)*Math.sin(b/2)**2;return Math.max(.1,+(12742*Math.asin(Math.sqrt(q))).toFixed(1))};
/* PHOTOS: optional overrides. Key = exact center name, value = list of image paths, e.g.
   'Barangka Elementary School':['images/barangka-front.jpg','images/barangka-gym.jpg']
   With no override the app looks for images/<name-as-filename>.jpg (see images/FILENAMES.txt). */
const PHOTOS={};
const slug=n=>n.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const EX=['jpg','jpeg','png','webp'];
window.imgErr=el=>{const n=+el.dataset.n,b=el.dataset.b;if(b&&n<EX.length){el.dataset.n=n+1;el.src=b+'.'+EX[n]}else{el.onerror=null;el.src='images/placeholder.svg';const f=el.closest('figure');if(f)f.classList.add('ph')}};
const gal=c=>{const alt=`Photo of ${esc(c.n)}`,cap='<figcaption class="mu s">Sample picture. A real photo has not been added yet.</figcaption>',L=PHOTOS[c.n];
return`<div class="gal">${L&&L.length?L.map(u=>`<figure class="fg"><img src="${esc(u)}" alt="${alt}" loading="lazy" onerror="imgErr(this)">${cap}</figure>`).join(''):`<figure class="fg"><img src="images/${slug(c.n)}.jpg" data-b="images/${slug(c.n)}" data-n="1" alt="${alt}" loading="lazy" onerror="imgErr(this)">${cap}</figure>`}</div>`};
const ph=c=>`<details class="phd"><summary>${IC('<path d="M4 8h3l2-3h6l2 3h3v11H4z"/><circle cx="12" cy="13" r="3.5"/>')} Photos of this center</summary>${gal(c)}</details>`;
const role=c=>{const b=BI[ui.br];return b.p.includes(c.id)?'Primary':b.n.includes(c.id)?'Nearby':''};
const grp=ids=>ids.map(id=>S.c.find(c=>c.id===id)).filter(Boolean);
const cc=c=>{const st=cs(c),k=BD[st][0],p=Math.min(100,Math.round(c.occ/c.cap*100));
return`<article class="card sh"><div class="row sp top"><div><p>${bg(st)}${role(c)?` <span class="tg">${role(c)}</span>`:''}</p><h3>${esc(c.n)}</h3><p class="loc"><b>Brgy. ${esc(c.a)}</b> · ${dist(c)} km away</p></div><div class="ring ${k}" style="--p:${p}"><span>${p}%</span></div></div><div class="hc"><div class="row sp"><span class="mu s">Occupancy headcount</span><span><b>${c.occ}</b> <span class="mu">/ ${c.cap}</span></span></div><div class="tr ${k}" aria-hidden="true"><i style="width:${p}%"></i></div><p class="mu s">${Math.max(0,c.cap-c.occ)} spaces left</p></div>${fr(c.u)}<div class="row sp"><div class="row">${c.ramp?'<span class="tg">Ramp</span>':'<span class="tg no">No ramp</span>'}${c.gn?'<span class="tg">CR</span>':''}${c.med?'<span class="tg">Medical</span>':''}${c.kid?'<span class="tg">Child-safe</span>':''}</div><button class="lk" data-a="nav" data-t="${tab}" data-s="ctr:${c.id}">View Info ›</button></div>${ph(c)}</article>`};
const LST=()=>{const q=ui.q.toLowerCase().trim(),f=ui.f,ok=c=>(!ui.hz||c.hz.includes(ui.hz))&&(!f.ramp||c.ramp)&&(!f.med||c.med)&&(!f.kid||c.kid)&&(!f.open||['AVAILABLE','NEARLY FULL'].includes(cs(c))),
so=ui.so==='space'?(a,b)=>(b.cap-b.occ)-(a.cap-a.occ):ui.so==='name'?(a,b)=>a.n.localeCompare(b.n):(a,b)=>dist(a)-dist(b),
sec=(t,L)=>`<h2>${t}</h2>${L.length?L.map(cc).join(''):'<p class="mu s">None match the filters.</p>'}`;
if(q){const L=S.c.filter(c=>(c.n+c.a).toLowerCase().includes(q)&&ok(c)).sort(so);return `<h2>Search results · all barangays</h2>${L.length?L.map(cc).join(''):'<p class="mu">No centers match. Try clearing filters.</p>'}`}
const b=BI[ui.br];return sec('Primary evacuation centers · Brgy. '+esc(ui.br),grp(b.p).filter(ok).sort(so))+sec('Nearby / neighboring centers',grp(b.n).filter(ok).sort(so))};
const V={
home:()=>{const al=S.al.find(a=>a.cat==='Emergency'),f=ui.f;
return`${al&&!ui.dis?`<div class="ban" role="status">${IC(HI[0])}<span><b>${esc(al.t)}</b> ${esc(al.b)}</span><button data-a="dis" aria-label="Dismiss alert">✕</button></div>`:''}<div class="card"><h3>What do I do now?</h3><button class="dgb" style="margin-top:10px" data-a="nav" data-t="home" data-s="danger">I’m in immediate danger</button><div class="chips"><button data-a="cat" data-c="General">I need assistance</button><button data-a="cat" data-c="Medical">I need medical help</button><button data-a="nav" data-t="relief">I need relief goods</button><button data-a="nav" data-t="home" data-s="info">Emergency info</button></div></div>
<div class="card"><div class="sf">${IC('<circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/>')}<input id="sq0" type="search" placeholder="Search shelter, school, or location…" aria-label="Search shelters" value="${esc(ui.q)}"></div><div class="two"><select id="br" aria-label="Your barangay">${brOpts(ui.br,'Your Barangay: ')}</select><select id="so" aria-label="Sort by">${[['near','Nearest'],['space','Most space'],['name','Name']].map(([v,l])=>`<option value="${v}"${v===ui.so?' selected':''}>${l}</option>`).join('')}</select></div><p class="mu s" style="margin:8px 0 0">Showing only the primary and nearby centers for your barangay. Distances are straight-line from the center of your barangay. Searching looks at all barangays.</p></div>
<div class="chips">${[['','All Shelters'],['flood','Flood'],['fire','Fire'],['quake','Earthquake']].map(([k,l])=>`<button class="chip" aria-pressed="${ui.hz===k}" data-a="hz" data-k="${k}">${l}</button>`).join('')}${[['open','Has space'],['ramp','Ramp'],['med','Medical'],['kid','Child-safe']].map(([k,l])=>`<button class="chip" aria-pressed="${!!f[k]}" data-a="flt" data-k="${k}">${l}</button>`).join('')}</div><div id="lst">${LST()}</div><p class="note s">Prototype data. Always follow instructions from barangay officials and rescue teams.</p>`},
map:()=>{const b=BI[ui.br],L2=grp([...b.p,...b.n]);
return`<div class="card"><label for="br" style="margin-top:0">Your barangay</label><select id="br">${brOpts(ui.br)}</select></div><div class="mw"><div id="lmap" class="lmap"></div><div id="mpop" class="mpop"></div></div><div class="row lgd s"><span class="ok">● Open</span><span class="wn">● Near capacity</span><span class="bd">● At capacity</span><span class="mu">● Unavailable</span></div><p class="mu s">Drag to move the map, pinch or use + / − to zoom. Solid pins are primary centers, dashed pins are nearby centers. Pins are placed around each barangay's center, not at exact street addresses. Occupancy numbers are simulated.</p><h2>Centers shown</h2>${L2.map((c,i)=>`<button class="big" data-a="sel" data-id="${c.id}"><span><b>${i+1} · ${esc(c.n)}</b><br><span class="mu s">${role(c)} · Brgy. ${esc(c.a)}</span></span></button>`).join('')}`},
assist:()=>`<p class="note s">Prototype. Submitting a request does not guarantee help. Medical requests are messages to volunteers, not medical triage, diagnosis or treatment advice. If someone is in danger, see Emergency contacts.</p><div class="card"><label for="rc">Type of help</label><select id="rc">${CATS.map(c=>`<option${c===ui.cat?' selected':''}>${c}</option>`).join('')}</select><label for="rd">What do you need? (no medical history or ID numbers)</label><textarea id="rd" rows="3" maxlength="200"></textarea><label for="rcn">Nearest center</label><select id="rcn">${co(ui.cn)}</select><button class="p" data-a="req">Submit request</button></div><p class="mu s">Status flow: PENDING → ASSIGNED → IN PROGRESS → RESOLVED</p><h2>My requests</h2>${S.req.length?S.req.map(r=>`<div class="card"><div class="row sp"><b>${r.id} · ${r.cat}</b>${bg(r.s)}</div><p>${esc(r.d)}</p><p class="mu s">${T(r.t)} · ${esc(S.c.find(c=>c.id===r.cid).n)} ${qs(r.qid)}</p></div>`).join(''):'<p>No requests yet.</p>'}`,
relief:()=>`<h2>Register a family</h2><p class="note s">Reduces confusion and duplicate handouts. Prototype QR only — not a secure or government ID system. Use fictional names.</p><div class="card"><label for="fh">Head of family (fictional name)</label><input id="fh" maxlength="40"><label for="fm">Number of members</label><input id="fm" type="number" min="1" max="20" inputmode="numeric"><label for="fc">Evacuation center</label><select id="fc">${co(ui.cn)}</select><div>${['Senior','Child','Pregnant','PWD'].map(n=>`<label class="ck"><input type="checkbox" class="nd" value="${n}">${n}</label>`).join('')}</div><button class="p" data-a="reg">Register family</button></div>
<h2>Family records</h2>${S.fam.length?S.fam.map(f=>`<details class="card"><summary>${f.id} · ${esc(f.h)} (${f.m})</summary>${qr(f.id)}<p class="s">Center: ${esc(S.c.find(c=>c.id===f.cid).n)}${f.needs.length?' · Needs: '+f.needs.join(', '):''}</p><p class="s">Last relief: ${f.rel?T(f.rel):'none yet'} ${qs(f.qid)}</p></details>`).join(''):'<p>No families registered yet.</p>'}
<h2>Volunteer: record distribution</h2>${S.fam.length?`<div class="card"><label for="df">Verify family (match the QR ID)</label><select id="df">${S.fam.map(f=>`<option value="${f.id}">${f.id} · ${esc(f.h)}</option>`).join('')}</select><label for="di">Item</label><select id="di">${S.inv.map(i=>`<option value="${i.id}">${esc(i.n)} (${i.q} left)</option>`).join('')}</select><label for="dq">Quantity</label><input id="dq" type="number" min="1" value="1" inputmode="numeric"><button class="p" data-a="dist">Distribute</button><p class="mu s">Camera scanning is not included; pick the ID shown under the family’s QR.</p></div>`:'<p>Register a family first.</p>'}`,
more:()=>{const p=S.q.filter(x=>x.s!=='SYNCHRONIZED').length;return`<div class="grid"><button class="big" data-a="nav" data-t="more" data-s="al">Alerts (demo)</button><button class="big" data-a="nav" data-t="more" data-s="info">Emergency information</button><button class="big" data-a="nav" data-t="more" data-s="coord">Coordinator mode</button><button class="big" data-a="nav" data-t="more" data-s="q">Pending actions (${p})</button><button class="big" data-a="nav" data-t="more" data-s="about">About, privacy and data</button></div><div class="card"><label class="ck"><input type="checkbox" id="sim" data-a="sim"${S.sim?' checked':''}> Demo: pretend I am offline</label><p class="mu s">Use this to test offline mode and sync.</p></div><button data-a="rst">Reset demo data</button>`}};
const SV={
danger:()=>`<ol><li>If it is safe to do so, move to higher ground or a safe place now.</li><li>Follow instructions from barangay officials and rescue teams.</li><li>Call your local emergency number (see Emergency contacts).</li></ol><p class="note">This app cannot call or alert rescuers. It is a prototype, not an emergency service.</p><button class="p" data-a="nav" data-t="home" data-s="info">Emergency contacts</button><button data-a="nav" data-t="map">Find an evacuation center</button>`,
ctr:id=>{const c=S.c.find(x=>x.id===id);return`<section class="card k-${BD[cs(c)][0]}"><div class="row sp"><h3>${esc(c.n)}</h3>${bg(cs(c))}</div><p class="mu s">${esc(c.a)}</p><div class="tr" aria-hidden="true"><i class="${BD[cs(c)][0]}" style="width:${Math.min(100,Math.round(c.occ/c.cap*100))}%"></i></div><p class="cnt"><b>${Math.max(0,c.cap-c.occ)}</b> spaces left <span class="mu">· ${c.occ} of ${c.cap} filled</span></p>${fr(c.u)}</section><h2>Photos</h2><div class="card">${gal(c)}</div><h2>Facilities</h2><div class="card">${FL.map(([k,l])=>`<p class="${c[k]?'ok':'mu'}">${c[k]?'✓ '+l:'– '+l+': not reported'}</p>`).join('')}<p>${esc(c.note)}</p></div><p class="note s">PROTOTYPE DATA — center names come from a Marikina evacuation list; capacity, headcount and facilities are simulated.</p><button class="p" data-a="here" data-t="assist" data-id="${c.id}">Request assistance here</button><button data-a="here" data-t="relief" data-id="${c.id}">Register family here</button>`},
info:()=>{const I=[['Before evacuation','Know your nearest center and route. Pack water, food, medicines, documents in a waterproof bag, a flashlight and a power bank. Charge phones. Agree on a family meeting point.'],['During evacuation','Leave early and follow official instructions. Do not walk or drive through floodwater. Keep away from fallen power lines. Help children, seniors and people with disabilities first.'],['Flood safety','Floodwater can hide hazards and carry disease. Turn off electricity only if told to and it is safe. Stay out of moving water.'],['After evacuation','Wait for the official all-clear before returning. Avoid contaminated water and check that the building is safe before going in.'],['Family safety','Keep your family together. Write contact numbers on paper. Register your family at the center so volunteers can find you.'],['Accessibility','Tell volunteers about mobility, vision, hearing or other needs. Ask for ramp access and accessible toilets. Keep medicines and assistive devices with you.'],['Water and sanitation','Drink only safe or boiled water. Wash hands with soap. Use designated toilets. Keep food covered.'],['Emergency contacts','National Emergency Hotline: 911 · Philippine Red Cross: 143 (carried over from the original prototype — verify with your barangay). Barangay contact: not added yet, ask your barangay.']];
return`${I.map((x,i)=>`<details class="card"${i?'':' open'}><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}<p class="mu s">General guidance for the prototype. Confirm with your LGU and national disaster agencies. Content last edited for this prototype build.</p>`},
al:()=>`<p class="note s">Every alert here is simulated. ${on()?'':'You are offline: new alerts cannot arrive. Earlier alerts stay readable.'}</p><div class="row">${['Service','Information'].map(k=>`<button class="chip" aria-pressed="${!!S.pref[k]}" data-a="pref" data-k="${k}">${k} alerts: ${S.pref[k]?'On':'Off'}</button>`).join('')}</div><p class="mu s">Emergency alerts stay on.</p>${S.al.filter(a=>a.cat==='Emergency'||S.pref[a.cat]).map(a=>`<div class="card"><p class="s"><b>${a.cat}</b> · ${T(a.at)}</p><h3>${esc(a.t)}</h3><p>${esc(a.b)}</p></div>`).join('')}`,
q:()=>`<p class="mu s">Actions taken offline wait here and send when you reconnect. Sync in this prototype is simulated on this device only.</p>${S.q.length?S.q.slice().reverse().map(x=>`<div class="card"><div class="row sp"><span>${esc(x.x)}</span>${bg(x.s)}</div>${x.s==='SYNC FAILED'?`<button data-a="retry" data-id="${x.id}">Retry</button>`:''}</div>`).join(''):'<p>Nothing pending.</p>'}`,
about:()=>`<div class="card"><p><b>What this is.</b> A school prototype for finding shelters, asking for help and recording relief. It is not an official emergency service and does not guarantee assistance.</p><p><b>What is stored.</b> Fictional family names, member counts, needs flags and requests are saved only in this browser (local storage) so the demo works offline. Nothing is sent to a server. Local storage is not a secure or shared emergency database.</p><p><b>Sync assumptions.</b> Offline actions are queued and marked SYNCED after a simulated delay. A real system would need a server database, sign-in and roles, a sync API with validation, push notifications, signed QR records and audit logs.</p><p><b>Not included.</b> Live GPS, map tiles, directions, camera QR scanning and real push notifications.</p></div>`,
coord:()=>{if(!S.coord)return`<p class="note s">Prototype gate only, not real authentication. Demo PIN: 1234</p><label for="pin">PIN</label><input id="pin" type="password" inputmode="numeric" maxlength="4"><button class="p" data-a="pin">Unlock</button>`;
const ev=S.c.reduce((a,c)=>a+c.occ,0),cp=S.c.reduce((a,c)=>a+c.cap,0),pr=S.req.filter(r=>r.s!=='RESOLVED').length,ls=S.inv.filter(i=>is(i)!=='IN STOCK').length;
return`<div class="card"><p><b>${ev}</b> evacuees of <b>${cp}</b> total capacity</p><p><b>${pr}</b> open requests · <b>${ls}</b> items low, critical or out</p>${fr(S.last)}</div>
<h2>Centers</h2><div class="card"><label for="cb" style="margin-top:0">Show centers for</label><select id="cb"><option value="ALL"${ui.cb==='ALL'?' selected':''}>All barangays</option>${brOpts(ui.cb)}</select></div>${(ui.cb==='ALL'?S.c:grp([...BI[ui.cb].p,...BI[ui.cb].n])).map(c=>`<div class="card"><div class="row sp"><b>${esc(c.n)}</b>${bg(cs(c))}</div><p>${c.occ} of ${c.cap}</p>${[-5,-1,1,5].map(d=>`<button data-a="hc" data-id="${c.id}" data-d="${d}" aria-label="${d<0?'Decrease':'Increase'} headcount by ${Math.abs(d)} at ${esc(c.n)}">${d<0?'− ':'+ '}${Math.abs(d)}</button>`).join('')}<button data-a="off" data-id="${c.id}">${c.off?'Mark available':'Mark temporarily unavailable'}</button></div>`).join('')}
<h2>Assistance requests</h2>${S.req.length?S.req.map(r=>`<div class="card"><div class="row sp"><b>${r.id} · ${r.cat}</b>${bg(r.s)}</div><p>${esc(r.d)}</p>${r.s!=='RESOLVED'?`<button data-a="adv" data-id="${r.id}">Move to next status</button>`:''}</div>`).join(''):'<p>No requests.</p>'}
<h2>Relief inventory</h2>${S.inv.map(i=>`<div class="card"><div class="row sp"><b>${esc(i.n)}: ${i.q}</b>${bg(is(i))}</div><p class="mu s">Updated ${T(i.u)}</p></div>`).join('')}<div class="card"><label for="si">Item</label><select id="si">${S.inv.map(i=>`<option value="${i.id}">${esc(i.n)}</option>`).join('')}</select><label for="sq">Quantity</label><input id="sq" type="number" min="1" value="10" inputmode="numeric"><button class="p" data-a="stk" data-d="1">Add stock</button><button data-a="stk" data-d="-1">Distribute</button></div>
<h2>Send demo alert</h2><div class="card"><label for="ac">Category</label><select id="ac"><option>Emergency</option><option>Service</option><option>Information</option></select><label for="at">Title</label><input id="at" maxlength="60"><button data-a="alt">Send demo alert</button></div>
<h2>Recent activity</h2>${S.act.length?S.act.slice(0,12).map(a=>`<p class="s">${T(a.t)} · ${esc(a.x)}</p>`).join(''):'<p>No activity yet.</p>'}<button data-a="lock">Lock coordinator mode</button>`}};
function R(){save();const b=$('#bar'),p=S.q.filter(x=>x.s!=='SYNCHRONIZED').length,sy=S.q.some(x=>x.s==='SYNCING');
b.className=on()?'':'off';
b.textContent=on()?(sy?'SYNCING — updating pending actions…':'ONLINE — Last synchronized: '+T(S.last)+(p?' · '+p+' pending':'')):'OFFLINE — Last synchronized: '+T(S.last)+' — Some information may be outdated'+(p?' · '+p+' pending sync':'');
document.querySelectorAll('nav button').forEach(x=>x.setAttribute('aria-current',x.dataset.t===tab?'page':'false'));
const [k,a]=sub.split(':'),h=sub?SV[k](a):V[tab]();
$('#ht').innerHTML=(sub?ST[k]:TT[tab])+(!sub&&tab==='home'?' <span class="nc">NCLC</span>':'');$('#hb').hidden=!sub;$('#lg').hidden=!!sub;$('#pl').textContent=on()?'Online':'Offline Mode';$('#pl').className='pl'+(on()?'':' off');
if(MAPI){try{MAPI.remove()}catch(e){}MAPI=null}$('#v').innerHTML=(ui.msg?`<div class="note" role="status">${ui.msg}</div>`:'')+h;document.documentElement.style.setProperty('--hh',$('#hd').offsetHeight+'px');if(tab==='map'&&!sub)initMap()}
let MAPI=null,VIS=[],MK={};
const ico=(c,i)=>L.divIcon({className:'',html:`<div class="mk ${BD[cs(c)][0]}${role(c)==='Nearby'?' nb':''}${c.id===ui.sel?' sel':''}">${i+1}</div>`,iconSize:[32,32],iconAnchor:[16,16]});
const pop=()=>{const el=$('#mpop');if(!el)return;const c=VIS.find(x=>x.id===ui.sel);
el.innerHTML=c?`<div class="card k-${BD[cs(c)][0]}"><div class="row sp"><p style="margin:0">${bg(cs(c))} ${role(c)?`<span class="tg">${role(c)}</span>`:''}</p><button class="ib" data-a="popx" aria-label="Close">✕</button></div><h3>${esc(c.n)}</h3><p class="loc">Brgy. ${esc(c.a)} · ${dist(c)} km away</p><p class="s"><b>${c.occ}</b> / ${c.cap} spaces filled (${Math.min(100,Math.round(c.occ/c.cap*100))}%)</p><button class="p" data-a="nav" data-t="map" data-s="ctr:${c.id}">View Card</button></div>`:''};
const paint=()=>VIS.forEach((c,i)=>MK[c.id]&&MK[c.id].setIcon(ico(c,i)));
const pick=(id,fly)=>{ui.sel=id;paint();pop();const c=VIS.find(x=>x.id===id);if(c&&MAPI)fly?MAPI.flyTo([c.lat,c.lng],Math.max(MAPI.getZoom(),16),{duration:.6}):MAPI.panTo([c.lat,c.lng])};
function initMap(){const el=$('#lmap');if(!el)return;
if(typeof L==='undefined'){el.innerHTML='<p class="note s" style="margin:12px">The map could not load. You may be offline the first time you open it. The list below still works.</p>';return}
const b=BI[ui.br];VIS=grp([...b.p,...b.n]);MK={};if(ui.sel&&!VIS.some(c=>c.id===ui.sel))ui.sel='';
const m=MAPI=L.map(el,{zoomControl:true,minZoom:10,maxZoom:19});
{const lt=(document.documentElement.dataset||{}).theme==='light',osm=()=>L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(m);
if(L.maplibreGL&&window.maplibregl){try{L.maplibreGL({style:'https://tiles.openfreemap.org/styles/'+(lt?'positron':'dark'),attribution:'<a href="https://openfreemap.org" target="_blank" rel="noopener">OpenFreeMap</a> &copy; <a href="https://www.openmaptiles.org/" target="_blank" rel="noopener">OpenMapTiles</a> Data from <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>'}).addTo(m)}catch(e){osm()}}else osm()}
const h=BP[ui.br];L.circleMarker(h,{radius:7,color:'#fff',weight:2,fillColor:'#3b82f6',fillOpacity:1}).addTo(m).bindTooltip('Brgy. '+ui.br+' (center)');
VIS.forEach((c,i)=>{MK[c.id]=L.marker([c.lat,c.lng],{icon:ico(c,i),title:c.n,alt:c.n}).addTo(m).on('click',()=>pick(c.id))});
if(ui.mv&&ui.mv.br===ui.br)m.setView(ui.mv.c,ui.mv.z);else m.fitBounds(L.latLngBounds([h,...VIS.map(c=>[c.lat,c.lng])]).pad(.25),{maxZoom:16});
m.on('moveend',()=>{const c=m.getCenter();ui.mv={br:ui.br,c:[c.lat,c.lng],z:m.getZoom()}});pop()}
const A={
nav:b=>go(b.dataset.t,b.dataset.s),back:()=>go(tab),sel:b=>{pick(b.dataset.id,1);const e=$('#lmap');if(e)e.scrollIntoView({behavior:'smooth',block:'center'})},popx:()=>{ui.sel='';paint();pop()},dis:()=>{ui.dis=1;R()},hz:b=>{ui.hz=b.dataset.k;R()},
cat:b=>{ui.cat=b.dataset.c;go('assist')},here:b=>{ui.cn=b.dataset.id;go(b.dataset.t)},
flt:b=>{ui.f[b.dataset.k]=!ui.f[b.dataset.k];R()},
pref:b=>{S.pref[b.dataset.k]=S.pref[b.dataset.k]?0:1;R()},
sim:()=>{S.sim=S.sim?0:1;R();sync()},
rst:()=>{S=seed();ui.msg='Demo data was reset.';go('home');ui.msg='Demo data was reset.';R()},
reg:()=>{const h=$('#fh').value.trim(),m=+$('#fm').value,c=S.c.find(x=>x.id===$('#fc').value);
if(!h||!(m>0))return msg('Enter the head of family (a fictional name) and the number of members.'),R();
const id='FAM-'+String(S.fam.length+1).padStart(4,'0'),over=c.occ+m>c.cap;c.occ+=m;c.u=Date.now();
S.fam.push({id,h,m,cid:c.id,needs:[...document.querySelectorAll('.nd:checked')].map(x=>x.value),rel:0,qid:log('Family '+id+' registered at '+c.n+' ('+m+')')});
msg(`Family ${id} registered. ${esc(c.n)} now shows ${c.occ} of ${c.cap}.${over?' This is over the listed capacity; consider another center.':''}`);R()},
dist:()=>{const f=S.fam.find(x=>x.id===$('#df').value),i=S.inv.find(x=>x.id===$('#di').value),q=+$('#dq').value;
if(!f||!i||!(q>0))return msg('Choose a family, an item and a quantity.'),R();
if(q>i.q)return msg(`Only ${i.q} of ${esc(i.n)} in stock. Nothing was recorded.`),R();
if(f.rel&&Date.now()-f.rel<4*36e5&&!ui.ok)return ui.ok=1,msg(`${f.id} already received relief at ${T(f.rel)}. Tap Distribute again to record another distribution.`),R();
ui.ok=0;i.q-=q;i.u=Date.now();f.rel=Date.now();f.qid=log('Relief: '+q+' × '+i.n+' to '+f.id);
msg(`Recorded ${q} × ${esc(i.n)} for ${f.id}. Stock is now ${i.q} (${is(i)}).`);R()},
req:()=>{const d=$('#rd').value.trim(),cat=$('#rc').value,cid=$('#rcn').value;
if(d.length<3)return msg('Please describe what you need in a few words.'),R();
const id='REQ-'+(1001+S.req.length);S.req.unshift({id,cat,d,cid,s:'PENDING',t:Date.now(),qid:log('Assistance request '+id+' ('+cat+')')});
ui.cat='General';msg(`Request ${id} saved with status PENDING.${on()?'':' You are offline, so it will send when you reconnect.'} Submitting does not guarantee assistance.`);R()},
pin:()=>{if($('#pin').value==='1234'){S.coord=1;msg('Coordinator mode unlocked (prototype).')}else msg('Incorrect PIN.');R()},
lock:()=>{S.coord=0;go('more')},
hc:b=>{const c=S.c.find(x=>x.id===b.dataset.id),d=+b.dataset.d;c.occ=Math.max(0,c.occ+d);c.u=Date.now();log('Headcount '+(d>0?'+':'')+d+' at '+c.n+' (now '+c.occ+')');R()},
off:b=>{const c=S.c.find(x=>x.id===b.dataset.id);c.off=c.off?0:1;c.u=Date.now();log(c.n+(c.off?' marked temporarily unavailable':' available again'));R()},
adv:b=>{const r=S.req.find(x=>x.id===b.dataset.id),o=['PENDING','ASSIGNED','IN PROGRESS','RESOLVED'];r.s=o[o.indexOf(r.s)+1];log(r.id+' → '+r.s);R()},
stk:b=>{const i=S.inv.find(x=>x.id===$('#si').value),q=+$('#sq').value,d=+b.dataset.d;
if(!(q>0))return msg('Enter a quantity greater than 0.'),R();
if(d<0&&q>i.q)return msg(`Only ${i.q} in stock. Nothing was recorded.`),R();
i.q+=d*q;i.u=Date.now();log((d>0?'Added ':'Distributed ')+q+' × '+i.n+' (now '+i.q+')');msg(`${esc(i.n)}: now ${i.q} (${is(i)}).`);R()},
alt:()=>{const t=$('#at').value.trim();if(!t)return msg('Enter a title for the demo alert.'),R();
S.al.unshift({id:Date.now(),cat:$('#ac').value,t:'DEMO ALERT: '+t,b:'Simulated alert created in Coordinator mode. This is not a real alert.',at:Date.now()});log('Demo alert sent: '+t);msg('Demo alert added to Alerts.');R()},
retry:b=>{const x=S.q.find(y=>y.id===b.dataset.id);if(x)x.s='PENDING SYNC';sync()}};
document.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(b&&b.tagName!=='INPUT'&&A[b.dataset.a])A[b.dataset.a](b)});
document.addEventListener('input',e=>{if(e.target.id==='sq0'){ui.q=e.target.value;$('#lst').innerHTML=LST()}});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='br'){ui.br=t.value;ui.sel='';R()}else if(t.id==='so'){ui.so=t.value;R()}else if(t.id==='cb'){ui.cb=t.value;R()}else if(t.id==='sim')A.sim()});
addEventListener('online',sync);addEventListener('offline',R);
$('#hb').innerHTML=IC('<path d="M15 5l-7 7 7 7"/>');$('#lg').innerHTML=IC(HI[1]);$('#pf').innerHTML=IC('<circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 4-6 8-6s8 2 8 6"/>');$('#nv').innerHTML=NV.map(n=>`<button data-a="nav" data-t="${n[0]}">${IC(n[2])}<span>${n[1]}</span></button>`).join('');
addEventListener('resize',()=>document.documentElement.style.setProperty('--hh',$('#hd').offsetHeight+'px'));
R();sync();

if('serviceWorker' in navigator&&location.protocol.startsWith('http')){addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}))}
